name: chess-looking_glass_oracle-environment
# conda env create --prefix ./env --file environment.yml
# conda env update --prefix ./env --file environment.yml --prune

channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults

dependencies:
  - python=3.10.8
  - numpy
  - pytorch
  - pytorch-cuda=11.8
  - transformers>=4.40.0
  - safetensors
  - pandas
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - -r requirements.txt